# Generated by Django 4.1.3 on 2022-12-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='became_client',
            field=models.BooleanField(default=False),
        ),
    ]
